Feature/50918 Toolbar
SnowdogApps/alpaca-storybook pull request #135
Opened 2019-03-18 12:28 UTC by jszczech

2019-03-21 14:41 UTC, szafran89 requested changes

2019-03-21 14:41 UTC, szafran89 commented on components/02-elements/banner/Banner.vue
> +        class="lazyload"
Imo you can remove it

2019-03-21 14:41 UTC, szafran89 commented on components/03-modules/pager/Pager.vue
>            aria-label="Go to next page"
move to prop

2019-03-21 14:41 UTC, szafran89 commented on components/03-modules/toolbar/Toolbar.stories.js
> +          :sortByLabel="toolbar.text"
https://eslint.vuejs.org/rules/attribute-hyphenation.html

2019-03-21 14:41 UTC, szafran89 commented on components/03-modules/toolbar/Toolbar.stories.js
> +          :sortByLabel="toolbar.text"
https://eslint.vuejs.org/rules/attribute-hyphenation.html

2019-03-25 05:31 UTC, jszczech commented on components/03-modules/toolbar/Toolbar.stories.js
> +          :sortByLabel="toolbar.text"
👍

2019-03-25 05:31 UTC, jszczech commented on components/03-modules/toolbar/Toolbar.stories.js
> +          :sortByLabel="toolbar.text"
👍

2019-03-25 05:32 UTC, jszczech commented on components/02-elements/banner/Banner.vue
> +        class="lazyload"
👍

2019-03-25 05:38 UTC, jszczech commented on components/03-modules/pager/Pager.vue
>            aria-label="Go to next page"
👍

2020-07-31 09:01 UTC, closed without merging