Feature/update link
SnowdogApps/alpaca-storybook pull request #277
Opened 2020-07-03 08:38 UTC by zuzannaszymanda

2020-07-03 10:50 UTC, anqaka requested changes
secodary variant has wrong styles, we need styles like in alpaca theme for M2, please check and adjust

2020-07-31 08:24 UTC, szafran89 requested changes

2020-07-31 08:24 UTC, szafran89 commented on src/atoms/link/Link.vue
> +<style lang="css" src="./Link.css" />
you can remove lang attr at all

2020-07-31 08:24 UTC, szafran89 commented on src/atoms/link/Link.vue
> +<style lang="css" src="./Link.css" />
please remove, then merge to update branch

2020-07-31 08:27 UTC, szafran89 requested changes

2020-07-31 08:27 UTC, szafran89 commented on src/atoms/link/Link.vue
>  }
please remove empty line below `name: 'AlpacaLink',`

2020-07-31 08:27 UTC, szafran89 commented
There is also issue related to UT, please check `yarn test`

2020-08-28 14:24 UTC, szafran89 approved these changes

2020-08-28 14:26 UTC, szafran89 commented
Looks like there is still issue related to UT, please `check yarn test`

2020-08-28 14:32 UTC, szafran89 commented
There is also no need to check the same thing in 2 tests
```
    expect(wrapper.is('a')).toBe(true)
    expect(wrapper.classes()).toContain('a-link')
```

2020-08-28 15:00 UTC, szafran89 approved these changes

2020-08-28 15:01 UTC, szafran89 commented
Ready to merge ;)

2020-08-28 15:03 UTC, merged